name: ChatGames
version: '1.4'
author: 'RareHyperIon'
description: 'A plugin aimed to add fun chat based games to your server.'
main: dev.rarehyperion.chatgames.ChatGamesSpigot
api-version: '1.21'
softdepend: [PlaceholderAPI]
commands:
  chatgames:
    aliases: [chatgame, cg]