<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>dev.rarehyperion.chatgames</groupId>
        <artifactId>chatgames-parent</artifactId>
        <version>1.4.6</version>
    </parent>


    <modelVersion>4.0.0</modelVersion>
    <artifactId>chatgames-sponge</artifactId>

    <dependencies>
        <dependency>
            <groupId>dev.rarehyperion.chatgames</groupId>
            <artifactId>chatgames-common</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.spongepowered</groupId>
            <artifactId>spongeapi</artifactId>
            <version>8.0.0</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>ChatGames-Sponge-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <artifactSet>
                                <includes>
                                    <include>dev.rarehyperion.chatgames:chatgames-common</include>
                                    <include>com.github.rarehyperionyt:chatgames-api</include>
                                    <include>redis.clients:jedis</include>
                                    <include>org.apache.commons:commons-pool2</include>
                                    <include>org.json:json</include>
                                    <include>com.google.code.gson:gson</include>
                                    <include>org.slf4j:slf4j-api</include>
                                </includes>
                            </artifactSet>
                            <relocations>
                                <relocation>
                                    <pattern>redis.clients.jedis</pattern>
                                    <shadedPattern>dev.rarehyperion.chatgames.libs.jedis</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.commons.pool2</pattern>
                                    <shadedPattern>dev.rarehyperion.chatgames.libs.commons.pool2</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google.gson</pattern>
                                    <shadedPattern>dev.rarehyperion.chatgames.libs.gson</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.json</pattern>
                                    <shadedPattern>dev.rarehyperion.chatgames.libs.json</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.yml</include>
                </includes>
                <filtering>true</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.json</include>
                </includes>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>
